version: "3.8"

services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend/
    container_name: backend_fastapi
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    command: uvicorn main:app --host 0.0.0.0 --port 3000

  frontend:
    build:
      context: ./frontend/
    container_name: frontend_react
    ports:
      - 8000:3000
    command: npm start
